name: capp_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route:
  cupertino_icons:
  dartz:
  equatable:
  flutter_riverpod:
  shared_preferences:
  uuid:
  dio:
  easy_localization: ^3.0.7
  flutter_svg: ^2.0.17
  clean_calendar:
    path: ./clean_calendar_master


dev_dependencies:
  build_runner:
  auto_route_generator:
  flutter_lints:

  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
          weight: 400
        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
  assets:
    - assets/translations/
    - assets/icons/
    - assets/images/
